(()=>{window.addEventListener('DOMContentLoaded',()=>{
const PROFILE_KEY='erc_profile_v1',RESULTS_KEY='erc_daily_results_v1';
const el=id=>document.getElementById(id);const main=document.querySelector('main.wrap');
const style=document.createElement('style');style.textContent=`
.dailyModal{position:fixed;inset:0;background:rgba(5,8,20,.88);display:flex;align-items:center;justify-content:center;z-index:100;padding:20px}.dailyModalBox{width:min(420px,100%);background:#171b2e;border:1px solid #2e3558;border-radius:20px;padding:24px;box-shadow:0 20px 60px #0008}.dailyInput{width:100%;padding:14px;border-radius:12px;border:1px solid #384166;background:#11162b;color:#fff;font-size:18px;margin:10px 0 14px}.userRow{display:flex;justify-content:flex-end;margin:-6px 0 12px}.userPill{background:#202640;border:1px solid #2e3558;color:#dce3ff;border-radius:999px;padding:8px 12px;cursor:pointer}.dailyStage{margin-top:14px}.dailyEnglish{font-size:27px;line-height:1.4;font-weight:800;text-align:center;padding:26px 8px}.dailyReveal{width:100%;padding:16px;border-radius:14px;background:#252d4c;color:#fff;border:1px solid #384166;font-weight:800}.dailyOptions{display:grid;gap:10px;margin-top:12px}.dailyOpt{padding:15px;text-align:left;border-radius:13px;background:#222946;color:#fff;border:1px solid #30395f}.dailyOpt.good{border-color:#49d17d;background:#49d17d22}.dailyOpt.bad{border-color:#ff6b7a;background:#ff6b7a22}.dailyGridBank{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.dailyItem{padding:9px 11px;border-radius:10px;background:#252d4c;color:#fff;border:1px solid #384166}.dailyItem.sel{outline:2px solid #7aa2ff}.dailyGrid{display:grid;gap:8px;margin:12px 0}.dailyCell{min-height:88px;border:1px solid #384166;border-radius:12px;background:#1d233b;color:#fff;padding:8px;display:flex;align-items:center;justify-content:center;font-weight:800;position:relative}.dailyCell small{position:absolute;left:7px;top:5px;color:#8fa1d9;font-size:10px}.leaderTable{width:100%;border-collapse:collapse;margin-top:14px}.leaderTable th,.leaderTable td{padding:10px 8px;border-bottom:1px solid #2e3558;text-align:left}.leaderTable th:nth-child(1),.leaderTable td:nth-child(1){text-align:center;width:54px}.dailySelect{background:#202640;color:#fff;border:1px solid #384166;border-radius:10px;padding:9px}.dailySummary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.dailySummary>div{background:#202640;border:1px solid #2e3558;border-radius:13px;padding:13px;text-align:center}.dailySummary strong{display:block;font-size:24px}.backendNote{margin-top:10px;font-size:12px;color:#aab2d5}.dailyHidden{display:none!important}@media(max-width:600px){.dailyEnglish{font-size:22px}.dailySummary{grid-template-columns:1fr}.leaderTable{font-size:13px}}
`;document.head.appendChild(style);
function uuid(){return crypto.randomUUID?crypto.randomUUID():'d-'+Date.now()+'-'+Math.random().toString(36).slice(2)}
function getProfile(){try{return JSON.parse(localStorage.getItem(PROFILE_KEY))}catch{return null}}
function saveProfile(name){const old=getProfile();const p={displayName:name.trim(),deviceId:old?.deviceId||uuid()};localStorage.setItem(PROFILE_KEY,JSON.stringify(p));return p}
function getResults(){try{return JSON.parse(localStorage.getItem(RESULTS_KEY))||{}}catch{return{}}}
function putResult(date,r){const all=getResults();if(!all[date])all[date]=r;localStorage.setItem(RESULTS_KEY,JSON.stringify(all));return all[date]}
function tokyoLogicalDate(now=Date.now()){const shifted=new Date(now-5*3600000);const f=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit'});return f.format(shifted)}
function dayDiff(a,b){return Math.floor((Date.parse(a+'T00:00:00Z')-Date.parse(b+'T00:00:00Z'))/86400000)}
const today=tokyoLogicalDate();let dIndex=Math.max(0,dayDiff(today,window.DAILY_START||today));
function releaseOldDaily(){if(!window.DAILY_PACKS)return;const n=Math.min(dIndex,DAILY_PACKS.length);for(let i=0;i<n;i++){for(const q of DAILY_PACKS[i].clues){if(!BANK.some(x=>x.id===q.id))BANK.push({...q,dailyOnly:false,fromDaily:true})}const m=DAILY_PACKS[i].mini;if(m&&!MINI_PUZZLES.some(x=>x.id===m.id))MINI_PUZZLES.push({...m,fromDaily:true})}if(el('bankCount'))el('bankCount').textContent=BANK.length;if(el('miniCount'))el('miniCount').textContent=MINI_PUZZLES.length}
releaseOldDaily();
function hideAll(){['homeScreen','quizScreen','resultScreen','miniScreen','dailyScreen','leaderScreen'].forEach(id=>el(id)?.classList.add('hidden'))}
function goHome2(){hideAll();el('homeScreen')?.classList.remove('hidden');refreshHome()}
function fmtTime(ms){return (ms/1000).toFixed(1)+'s'}
function scoreOf(r){return (r.clueScore||0)+(r.miniCorrect?1:0)}
function showLogin(force=false){if(getProfile()&&!force)return;let m=el('dailyLoginModal');if(!m){m=document.createElement('div');m.id='dailyLoginModal';m.className='dailyModal';m.innerHTML=`<div class="dailyModalBox"><h2>名前を入力</h2><p class="muted">Daily Challengeとランキングで使う表示名です。メール・パスワードは不要。</p><input id="dailyNameInput" class="dailyInput" maxlength="24" placeholder="例：Hanaoka"><button id="dailyNameSave" class="primary" style="width:100%">この名前で始める</button><p class="small muted">※ 名前だけの簡易ログインです。共有ランキングの本人確認は強くありません。</p></div>`;document.body.appendChild(m);el('dailyNameSave').onclick=()=>{const v=el('dailyNameInput').value.trim();if(!v)return;saveProfile(v);m.remove();refreshHome()};el('dailyNameInput').addEventListener('keydown',e=>{if(e.key==='Enter')el('dailyNameSave').click()})}else m.classList.remove('dailyHidden');const p=getProfile();if(p)el('dailyNameInput').value=p.displayName}
function injectHome(){const home=el('homeScreen'),grid=home?.querySelector('.modegrid');if(!grid||el('dailyHomeCard'))return;const u=document.createElement('div');u.className='userRow';u.innerHTML=`<button id="userPill" class="userPill">👤</button>`;home.insertBefore(u,grid);el('userPill').onclick=()=>showLogin(true);
const d=document.createElement('div');d.id='dailyHomeCard';d.className='modecard';d.innerHTML=`<h2>Daily Challenge</h2><p class="small muted">新作Clue 10問 + Mini Puzzle 1問。毎朝5:00 JST更新。</p><button class="primary" id="dailyStartBtn">今日のDaily</button><p class="small muted" id="dailyStatus"></p>`;grid.appendChild(d);
const l=document.createElement('div');l.className='modecard';l.innerHTML=`<h2>Leaderboard</h2><p class="small muted">今日と過去日のDailyランキングを確認。</p><button class="primary" id="leaderBtn">ランキングを見る</button><p class="small muted">Score優先 → 同点はTime順</p>`;grid.appendChild(l);el('dailyStartBtn').onclick=startDaily;el('leaderBtn').onclick=showLeaderboard}
function refreshHome(){injectHome();const p=getProfile();if(el('userPill'))el('userPill').textContent='👤 '+(p?.displayName||'名前を入力');const r=getResults()[today];if(el('dailyStatus'))el('dailyStatus').textContent=r?`${today} 完了：${scoreOf(r)}/11・${fmtTime(r.totalTimeMs)}`:`${today} 未挑戦`;if(el('dailyStartBtn'))el('dailyStartBtn').textContent=r?'今日の結果を見る':'今日のDaily'}
function makeScreens(){if(!el('dailyScreen')){const s=document.createElement('section');s.id='dailyScreen';s.className='card hidden';s.innerHTML=`<div class="toprow"><div><span class="badge" id="dailyDate"></span> <span class="badge" id="dailyProgress"></span></div><span class="badge" id="dailyTimer">0.0 s</span></div><h2>Daily Challenge</h2><div id="dailyStage" class="dailyStage"></div><div class="actions"><button class="secondary" id="dailyHomeBtn">モード選択へ</button></div>`;main.insertBefore(s,document.querySelector('footer'));el('dailyHomeBtn').onclick=goHome2}
if(!el('leaderScreen')){const s=document.createElement('section');s.id='leaderScreen';s.className='card hidden';s.innerHTML=`<div class="toprow"><h2>Daily Leaderboard</h2><select id="leaderDate" class="dailySelect"></select></div><div id="leaderBody"></div><div class="backendNote" id="leaderBackendNote"></div><div class="actions"><button class="secondary" id="leaderHomeBtn">モード選択へ</button></div>`;main.insertBefore(s,document.querySelector('footer'));el('leaderHomeBtn').onclick=goHome2;el('leaderDate').onchange=loadLeaderboard}}
makeScreens();injectHome();
let daily={};function packForToday(){if(!DAILY_PACKS?.length)return null;return DAILY_PACKS[dIndex%DAILY_PACKS.length]}
function startDaily(){const existing=getResults()[today];if(existing){showDailyResult(existing);return}const p=getProfile();if(!p){showLogin();return}const pack=packForToday();if(!pack){alert('Daily問題がまだありません');return}daily={pack,idx:0,clueScore:0,readingMs:0,answerMs:0,miniCorrect:false,miniMs:0,started:performance.now(),qStart:0,revealAt:0,miniStart:0,miniSelected:null,miniCells:[]};hideAll();el('dailyScreen').classList.remove('hidden');el('dailyDate').textContent=today;renderDailyClue();tickDaily()}
let dailyRaf=null;function tickDaily(){cancelAnimationFrame(dailyRaf);const f=()=>{if(!el('dailyScreen')?.classList.contains('hidden')){el('dailyTimer').textContent=((performance.now()-daily.started)/1000).toFixed(1)+' s';dailyRaf=requestAnimationFrame(f)}};dailyRaf=requestAnimationFrame(f)}
function renderDailyClue(){if(daily.idx>=10){renderDailyMini();return}const q=daily.pack.clues[daily.idx];daily.qStart=performance.now();daily.revealAt=0;el('dailyProgress').textContent=`Clue ${daily.idx+1}/10`;el('dailyStage').innerHTML=`<div class="badge">${q.cat}</div><div id="dailyEnglish" class="dailyEnglish"></div><button id="dailyReveal" class="dailyReveal">意味を理解した → 選択肢を表示</button><div id="dailyOpts" class="dailyOptions dailyHidden"></div>`;el('dailyEnglish').textContent=q.q;const opts=[q.a,...q.w].sort(()=>Math.random()-.5);opts.forEach(t=>{const b=document.createElement('button');b.className='dailyOpt';b.textContent=t;b.onclick=()=>answerDailyClue(b,t,q);el('dailyOpts').appendChild(b)});el('dailyReveal').onclick=()=>{if(daily.revealAt)return;daily.revealAt=performance.now();daily.readingMs+=daily.revealAt-daily.qStart;el('dailyEnglish').classList.add('dailyHidden');el('dailyReveal').classList.add('dailyHidden');el('dailyOpts').classList.remove('dailyHidden')}}
function answerDailyClue(btn,t,q){if(!daily.revealAt)return;const ms=performance.now()-daily.revealAt;daily.answerMs+=ms;const correct=t===q.a;if(correct)daily.clueScore++;[...el('dailyOpts').children].forEach(b=>{b.disabled=true;if(b.textContent===q.a)b.classList.add('good')});if(!correct)btn.classList.add('bad');setTimeout(()=>{daily.idx++;renderDailyClue()},correct?250:550)}
function renderDailyMini(){const m=daily.pack.mini;daily.miniStart=performance.now();el('dailyProgress').textContent='Mini Puzzle';const clues=m.clues.map((c,i)=>`<li>${c}</li>`).join('');el('dailyStage').innerHTML=`<div class="badge">${m.category}</div><p>${m.setup}</p><ol class="cluelist">${clues}</ol><div class="miniQuestion">${m.question}</div><div id="dailyMiniArea"></div>`;if(m.mode==='grid-placement')renderDailyGrid(m);else{const a=el('dailyMiniArea');a.className='dailyOptions';[...m.choices].sort(()=>Math.random()-.5).forEach(t=>{const b=document.createElement('button');b.className='dailyOpt';b.textContent=t;b.onclick=()=>finishDailyMini(t===m.answer);a.appendChild(b)})}}
function renderDailyGrid(m){daily.miniCells=Array(m.rows*m.cols).fill(null);daily.miniSelected=null;const a=el('dailyMiniArea');a.innerHTML=`<p class="small muted">アイテムをタップ → マスをタップ。配置済みマスをタップすると拾い直せます。</p><div id="dailyGridBank" class="dailyGridBank"></div><div id="dailyGrid" class="dailyGrid" style="grid-template-columns:repeat(${m.cols},1fr)"></div><button id="dailyGridCheck" class="primary" disabled>配置を判定</button>`;m.items.forEach(x=>{const b=document.createElement('button');b.className='dailyItem';b.textContent=x;b.onclick=()=>{daily.miniSelected=x;paintGrid(m)};el('dailyGridBank').appendChild(b)});for(let i=0;i<daily.miniCells.length;i++){const c=document.createElement('button');c.className='dailyCell';c.onclick=()=>{if(daily.miniCells[i]){daily.miniSelected=daily.miniCells[i];daily.miniCells[i]=null}else if(daily.miniSelected){const old=daily.miniCells.indexOf(daily.miniSelected);if(old>=0)daily.miniCells[old]=null;daily.miniCells[i]=daily.miniSelected;daily.miniSelected=null}paintGrid(m)};el('dailyGrid').appendChild(c)};el('dailyGridCheck').onclick=()=>{const ok=daily.miniCells.every((x,i)=>x===m.answer[i]);finishDailyMini(ok)};paintGrid(m)}
function paintGrid(m){[...el('dailyGridBank').children].forEach(b=>{b.classList.toggle('sel',b.textContent===daily.miniSelected);b.style.opacity=daily.miniCells.includes(b.textContent)?'.45':'1'});[...el('dailyGrid').children].forEach((c,i)=>{const r=Math.floor(i/m.cols),col=i%m.cols;c.innerHTML=`<small>${r===0?'upper':'lower'}-${['left','middle','right'][col]||('c'+(col+1))}</small>${daily.miniCells[i]||''}`});el('dailyGridCheck').disabled=daily.miniCells.some(x=>!x)}
function finishDailyMini(correct){daily.miniMs=performance.now()-daily.miniStart;daily.miniCorrect=correct;const r={date:today,displayName:getProfile().displayName,deviceId:getProfile().deviceId,clueScore:daily.clueScore,miniCorrect:correct,readingTimeMs:Math.round(daily.readingMs),answerTimeMs:Math.round(daily.answerMs),miniTimeMs:Math.round(daily.miniMs),totalTimeMs:Math.round(daily.readingMs+daily.answerMs+daily.miniMs),completedAt:new Date().toISOString()};putResult(today,r);submitResult(r);showDailyResult(r)}
function showDailyResult(r){hideAll();el('dailyScreen').classList.remove('hidden');el('dailyDate').textContent=r.date||today;el('dailyProgress').textContent='Complete';el('dailyTimer').textContent=fmtTime(r.totalTimeMs);el('dailyStage').innerHTML=`<h2>Daily Result</h2><div class="dailySummary"><div><span class="muted">Score</span><strong>${scoreOf(r)}/11</strong></div><div><span class="muted">Clue</span><strong>${r.clueScore}/10</strong></div><div><span class="muted">Time</span><strong>${fmtTime(r.totalTimeMs)}</strong></div></div><p>Mini Puzzle: <b class="${r.miniCorrect?'ok':'ng'}">${r.miniCorrect?'✓ Correct':'✗ Incorrect'}</b></p><div class="actions"><button id="dailyLeaderNow" class="primary">この日のランキング</button></div>`;el('dailyLeaderNow').onclick=()=>showLeaderboard(r.date||today);refreshHome()}
let sbClient=null;async function getSupabase(){const c=window.ER_SUPABASE_CONFIG;if(!c?.url||!c?.anonKey)return null;if(sbClient)return sbClient;if(!window.supabase){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=res;s.onerror=rej;document.head.appendChild(s)})}sbClient=window.supabase.createClient(c.url,c.anonKey);let {data:{session}}=await sbClient.auth.getSession();if(!session){const x=await sbClient.auth.signInAnonymously();if(x.error)throw x.error}return sbClient}
async function submitResult(r){try{const sb=await getSupabase();if(!sb)return;const {data:{user}}=await sb.auth.getUser();await sb.from('daily_results').insert({user_id:user.id,display_name:r.displayName,daily_date:r.date,clue_score:r.clueScore,mini_correct:r.miniCorrect,score:scoreOf(r),reading_time_ms:r.readingTimeMs,answer_time_ms:r.answerTimeMs,mini_time_ms:r.miniTimeMs,total_time_ms:r.totalTimeMs})}catch(e){console.warn('Leaderboard submit failed',e)}}
function dateList(){const arr=[];const start=Date.parse((window.DAILY_START||today)+'T00:00:00Z'),end=Date.parse(today+'T00:00:00Z');for(let t=end;t>=start&&arr.length<60;t-=86400000)arr.push(new Date(t).toISOString().slice(0,10));return arr}
function showLeaderboard(date=today){hideAll();el('leaderScreen').classList.remove('hidden');const sel=el('leaderDate');sel.innerHTML='';dateList().forEach(d=>{const o=document.createElement('option');o.value=d;o.textContent=d;o.selected=d===date;sel.appendChild(o)});loadLeaderboard()}
async function loadLeaderboard(){const date=el('leaderDate').value;el('leaderBody').innerHTML='<p class="muted">Loading...</p>';let rows=[];let shared=false;try{const sb=await getSupabase();if(sb){const {data,error}=await sb.from('daily_results').select('display_name,score,clue_score,mini_correct,total_time_ms,completed_at').eq('daily_date',date).order('score',{ascending:false}).order('total_time_ms',{ascending:true});if(error)throw error;rows=data||[];shared=true}}catch(e){console.warn(e)}if(!shared){const r=getResults()[date];if(r)rows=[{display_name:r.displayName,score:scoreOf(r),clue_score:r.clueScore,mini_correct:r.miniCorrect,total_time_ms:r.totalTimeMs}]}renderLeaderboard(rows);el('leaderBackendNote').textContent=shared?'共有ランキングに接続中。':'現在は端末内の自分の結果のみ表示。Supabase接続後にチーム共有ランキングへ切り替わります。'}
function renderLeaderboard(rows){if(!rows.length){el('leaderBody').innerHTML='<p class="muted">この日の記録はまだありません。</p>';return}let h='<table class="leaderTable"><thead><tr><th>#</th><th>Name</th><th>Score</th><th>Time</th></tr></thead><tbody>';rows.forEach((r,i)=>h+=`<tr><td>${i+1}</td><td>${escapeHtml(r.display_name||'—')}</td><td>${r.score}/11</td><td>${fmtTime(r.total_time_ms)}</td></tr>`);h+='</tbody></table>';el('leaderBody').innerHTML=h}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
refreshHome();if(!getProfile())showLogin();
});})();