(()=>{
const Q=(id,cat,q,a,w,target,trap)=>({id,cat,q,a,w,target,trap,dailyOnly:true});
const P=[];
P.push({clues:[
Q('d0_01','Grid / Placement','The compass is directly beneath the map.','コンパスは地図と同じ列で、その1マス下にある。',['コンパスは地図より下なら何マス離れてもよい。','コンパスは地図の斜め下にある。','コンパスは地図の1マス上にある。'],'directly beneath','directly-vs-somewhere'),
Q('d0_02','Grid / Placement','Neither the apple nor the pear occupies a corner cell.','リンゴも梨も隅のマスにはない。',['リンゴか梨のどちらか一方だけが隅にある。','リンゴと梨は両方隅にある。','リンゴは隅ではないが梨は隅でもよい。'],'neither ... nor','neither-nor'),
Q('d0_03','Conditional','Maya is selected only if Noah is selected.','マヤが選ばれるなら、ノアも選ばれている必要がある。',['ノアが選ばれるならマヤも必ず選ばれる。','マヤとノアは必ず両方選ばれる。','マヤとノアの一方だけが選ばれる。'],'only if','only-if-reversal'),
Q('d0_04','Scheduling','The audit takes place no later than Thursday.','監査は木曜日までに行われる。木曜も含む。',['監査は木曜より後に行われる。','監査は木曜ちょうどに限る。','監査は金曜以降に行われる。'],'no later than','bound-direction'),
Q('d0_05','Ordering / Ranking','Exactly one contestant finishes between Leo and Mina.','レオとミナの間の順位にはちょうど1人いる。',['レオとミナは隣り合う。','レオとミナの間には2人いる。','レオとミナの順位差は1である。'],'exactly one between','gap-vs-distance'),
Q('d0_06','Assignment / Matching','Of Iris and the chef, one chose green and the other chose yellow.','アイリスとシェフは、一方が緑、もう一方が黄色を選んだ。どちらがどちらかは未確定。',['アイリスが緑、シェフが黄色と確定する。','アイリスが黄色、シェフが緑と確定する。','2人とも同じ色を選んだ。'],'one ... the other','one-the-other'),
Q('d0_07','Mixed / Quantifier','All but two of the eight lockers are occupied.','8個のロッカーのうち6個が使用中である。',['8個のうち2個が使用中である。','少なくとも6個が使用中なら7個や8個でもよい。','8個すべてが使用中である。'],'all but two','all-but-n'),
Q('d0_08','Grid / Placement','The lamp is somewhere to the left of the key in the same row.','ランプは鍵と同じ行で左側にあるが、隣とは限らない。',['ランプは鍵の左隣に限る。','ランプは鍵より左なら別の行でもよい。','ランプは鍵の右側にある。'],'somewhere to the left','somewhere-vs-immediate'),
Q('d0_09','Selection / Grouping','Either Ava or Ben must be selected, but not both.','アヴァとベンのうち、ちょうど一方だけを選ぶ。',['少なくとも一方を選べば両方でもよい。','2人とも選ばなければならない。','2人とも選んではならない。'],'either ... but not both','exclusive-or'),
Q('d0_10','Grid / Placement','The star and the moon occupy opposite corners of the grid.','星と月は互いに対角となる2つの隅にある。',['星と月は隣り合う2つの隅にある。','星と月は外周ならどこでもよい。','星と月は同じ列にある。'],'opposite corners','corner-relation')],mini:{id:'daily_m0',mode:'grid-placement',category:'Daily / Object Placement',englishDifficulty:3,logicDifficulty:2,rows:2,cols:3,items:['Anchor','Bell','Candle','Drum','Emerald','Feather'],setup:'Place the six objects into a 2×3 grid.',clues:['The Bell is in the middle cell of the top row.','The Emerald is directly below the Bell.','The Anchor is immediately to the left of the Bell.','The Feather is directly below the Candle.','The Drum is directly below the Anchor.'],question:'Place all six objects in their correct cells.',answer:['Anchor','Bell','Candle','Drum','Emerald','Feather'],key:'Bellを上段中央に固定。Anchorが左隣なので残る上段右がCandle。3本の縦対応で下段が決まります。',first:'middle cell of the top row を最優先で固定します。',expressions:['middle cell of the top row','directly below','immediately to the left of']}});
P.push({clues:[
Q('d1_01','Grid / Placement','The key is on the border of the grid but not in a corner.','鍵は外周にあるが、隅のマスではない。',['鍵は四隅のどれかにある。','鍵は内側のマスにある。','鍵は左端に限る。'],'border but not corner','edge-vs-corner'),
Q('d1_02','Ordering / Ranking','Nina finished immediately ahead of Omar.','ニナはオマーの1つ前の順位でゴールした。',['ニナはオマーより前なら何位離れてもよい。','ニナはオマーの1つ後ろである。','2人の間に1人いる。'],'immediately ahead of','adjacent-order'),
Q('d1_03','Conditional','Unless Priya attends, Quinn must attend.','プリヤが参加しないなら、クインは参加しなければならない。',['プリヤが参加するならクインも参加する。','クインが参加しないならプリヤも参加しない。','プリヤとクインは必ず一緒に参加する。'],'unless','unless-direction'),
Q('d1_04','Grid / Placement','The red tile is one row above the blue tile.','赤いタイルは青いタイルよりちょうど1行上にある。列が同じとは限らない。',['赤いタイルは青の真上1マスにある。','赤は青より2行上にある。','赤は青より1行下にある。'],'one row above','row-offset-vs-direct'),
Q('d1_05','Scheduling','The interview is scheduled sometime after Tuesday but before Friday.','面接は水曜か木曜に予定されている。',['面接は火曜から金曜までで両端も含む。','面接は金曜以降である。','面接は火曜以前である。'],'after ... before','exclusive-range'),
Q('d1_06','Truth-teller / Liar','Exactly one of Alice and Bob is telling the truth.','アリスとボブのうち真実を言っているのはちょうど1人。',['2人とも真実を言っている。','少なくとも1人が真実なら2人ともでもよい。','2人とも嘘をついている。'],'exactly one','exclusive-truth'),
Q('d1_07','Selection / Grouping','Cara and Diego are either both selected or both rejected.','カーラとディエゴは2人とも選ばれるか、2人とも選ばれない。',['ちょうど一方だけ選ばれる。','少なくとも一方は必ず選ばれる。','カーラだけは必ず選ばれる。'],'both or neither','same-selection'),
Q('d1_08','Grid / Placement','The coin is diagonally below and to the right of the book.','コインは本から見て右下の斜め隣にある。',['コインは本の真下にある。','コインは本の右隣にある。','コインは本より右下方向なら何マス離れてもよい。'],'diagonally below and to the right','diagonal-direction'),
Q('d1_09','Mixed / Quantifier','No fewer than four teams must advance.','少なくとも4チームが進出しなければならない。',['最大4チームまで進出できる。','ちょうど4チームだけ進出する。','4チーム未満でなければならない。'],'no fewer than','at-least-vs-at-most'),
Q('d1_10','Assignment / Matching','Rita, the doctor, and the person assigned Room 3 are all different people.','リタ、医師、3号室担当者は互いに別の3人である。',['リタが医師である。','医師が3号室担当者である。','3者のうち2者だけ別人ならよい。'],'all different people','all-different')],mini:{id:'daily_m1',category:'Daily / Ordering',englishDifficulty:3,logicDifficulty:2,setup:'Ava, Ben, Cara, Diego, and Eli finish a race in different positions from 1st to 5th.',clues:['Ben finishes immediately after Ava.','Cara finishes two places behind Ben.','Eli finishes last.','Diego finishes ahead of Ava.'],question:'Who finishes second?',choices:['Ava','Ben','Cara','Diego'],answer:'Ava',key:'Eli=5。CaraがBenの2つ後ろなのでBenは2以下では置きにくく、Diego>Ava>Benの連鎖と合わせると Diego–Ava–Ben–Cara–Eli に確定。',first:'Ben–Caraの位置差2と、Diego>Ava>Benの連鎖を重ねます。',expressions:['immediately after','two places behind','ahead of']}});
P.push({clues:[
Q('d2_01','Grid / Placement','The circle is flanked by the square and the triangle.','円の左右両隣に四角形と三角形がいる。左右どちらがどちらかは未確定。',['円は四角形と三角形のどちらか一方にだけ隣接する。','円は2つより左にある。','四角形と三角形が同じマスにある。'],'flanked by','two-sided-adjacency'),
Q('d2_02','Conditional','Whenever Leo attends, Mina attends as well.','レオが参加するたび、ミナも参加する。つまりLeo→Mina。',['ミナが参加すればレオも参加する。','2人は必ず参加する。','ちょうど一方だけ参加する。'],'whenever','conditional-direction'),
Q('d2_03','Scheduling','The demo is scheduled on one of the two days immediately following the audit.','デモは監査の翌日か翌々日のどちらかに行われる。',['デモは監査の直後の日に限る。','デモは監査より前の2日間のどちらか。','監査とデモの間には必ず2日ある。'],'one of the two days immediately following','window-after'),
Q('d2_04','Ordering / Ranking','There are exactly two runners between Noah and Olivia.','ノアとオリビアの間にちょうど2人の走者がいる。',['2人の順位差は2である。','間には1人いる。','少なくとも2人いれば3人以上でもよい。'],'exactly two runners between','gap-vs-distance'),
Q('d2_05','Grid / Placement','The gem is in the second column from the right.','宝石は右から2番目の列にある。',['宝石は左から2番目の列にあると常に同じ意味である。','宝石は右端の列にある。','宝石は右から2マス離れた列にある。'],'second column from the right','ordinal-column'),
Q('d2_06','Selection / Grouping','At most one of Priya, Quinn, and Rosa may be selected.','プリヤ、クイン、ローザのうち選べるのは最大1人。0人でもよい。',['ちょうど1人は必ず選ぶ。','少なくとも1人を選ぶ。','最大2人まで選べる。'],'at most one of three','at-most'),
Q('d2_07','Assignment / Matching','The person with the blue badge is not Sam or Tina.','青いバッジの人はサムでもティナでもない。',['青いバッジはサムかティナのどちらか。','サムとティナは両方青いバッジ。','サムだけ除外され、ティナは青でもよい。'],'not A or B','negated-alternatives'),
Q('d2_08','Grid / Placement','The moon is somewhere above the star in the same column.','月は星と同じ列で、星より上にある。隣接とは限らない。',['月は星の真上1マスに限る。','月は星より上なら別の列でもよい。','月は星より下にある。'],'somewhere above in same column','somewhere-vs-direct'),
Q('d2_09','Mixed / Quantifier','At least two but no more than five boxes must be opened.','開ける箱は2個以上5個以下。',['2個以上5個未満。','ちょうど2個。','5個以上。'],'at least ... no more than','inclusive-bounds'),
Q('d2_10','Truth-teller / Liar','Neither of the first two statements is true.','最初の2つの発言はどちらも真ではない。つまり両方偽。',['最初の2つのうちちょうど一方が真。','2つとも真。','少なくとも一方は真。'],'neither ... is true','neither-truth')],mini:{id:'daily_m2',category:'Daily / Selection',englishDifficulty:4,logicDifficulty:2,setup:'Exactly three of Ava, Ben, Cara, Diego, and Eli are selected.',clues:['Ava is selected.','Ben is selected only if Cara is selected.','Unless Diego is selected, Ben is selected.','Cara and Eli cannot both be selected.'],question:'Who must be selected?',choices:['Ben','Cara','Diego','Eli'],answer:'Cara',key:'Diego不選択ならunlessでBen、Ben→CaraなのでCara。Diego選択の場合もAva+Diegoに加え、Benを外すなら3人目はCaraかEliだがEli単独では条件を満たす構成が残らず、全ケースでCaraが必要。',first:'unless と only if を矢印にして連結します。',expressions:['only if','unless','cannot both']}});
P.push({clues:[
Q('d3_01','Grid / Placement','The book is immediately to the right of the object in the upper-left corner.','本は左上隅の物の右隣にある。',['本は左上隅そのものにある。','本は左上隅より右なら何マス離れてもよい。','本は左上隅の下にある。'],'immediately right of referent','referential-adjacency'),
Q('d3_02','Ordering / Ranking','Uma ranks higher than Victor but lower than Wendy.','順位はウェンディ、ウマ、ビクターの順に高い。',['ウマが3人の中で最高。','ビクター、ウマ、ウェンディの順。','ウマは2人の両方より低い。'],'higher than ... lower than','comparative-chain'),
Q('d3_03','Conditional','Xavier can enter if and only if Yara enters.','ゼイビアが入れることとヤラが入れることは同値。どちらか一方だけは不可。',['Yara→Xavierだけで逆は不要。','Xavier→Yaraだけで逆は不要。','ちょうど一方だけ入れる。'],'if and only if','biconditional'),
Q('d3_04','Grid / Placement','The key and the lock are in different rows and different columns.','鍵と錠前は行も列も異なる。',['行だけ異なれば列は同じでもよい。','列だけ異なれば行は同じでもよい。','必ず斜め隣である。'],'different rows and columns','two-axis-difference'),
Q('d3_05','Scheduling','The lecture immediately precedes the workshop.','講演はワークショップの直前に行われる。',['講演はワークショップより前ならいつでもよい。','講演はワークショップの直後。','2つの間に1イベントある。'],'immediately precedes','adjacent-order'),
Q('d3_06','Selection / Grouping','If Rosa is not selected, Sam and Tina must both be selected.','ローザが不選択なら、サムとティナの両方を選ぶ必要がある。',['ローザが選択ならサムとティナも選ぶ。','ローザが不選択ならサムかティナの一方だけ。','サムとティナが選ばれたらローザは不選択。'],'if not ... both','conditional-consequent'),
Q('d3_07','Assignment / Matching','The guest from Kyoto chose neither tea nor coffee.','京都からの客は紅茶もコーヒーも選んでいない。',['紅茶かコーヒーのどちらかを選んだ。','両方選んだ。','紅茶だけは選んでいないがコーヒーはよい。'],'neither ... nor','neither-nor'),
Q('d3_08','Grid / Placement','The red and blue tokens are on opposite sides of the green token in the same row.','赤と青は緑と同じ行で、緑を挟んで左右反対側にある。',['赤と青は緑の同じ側にある。','3つは同じ列にある。','赤と青は必ず緑の両隣だと確定する。'],'opposite sides of','opposite-sides-vs-adjacent'),
Q('d3_09','Mixed / Quantifier','Exactly four of the six statements are true.','6つの発言のうち真なのはちょうど4つ。',['少なくとも4つ真なら5つや6つでもよい。','真は最大4つ。','偽が4つ。'],'exactly four of six','exact-count'),
Q('d3_10','Ordering / Ranking','Zoe is among the bottom three finishers.','ゾーイは下位3人のうちの1人。',['ゾーイは必ず最下位。','ゾーイは上位3人の1人。','ゾーイは下から3位ちょうど。'],'among the bottom three','bottom-n')],mini:{id:'daily_m3',mode:'grid-placement',category:'Daily / Object Placement',englishDifficulty:4,logicDifficulty:2,rows:2,cols:3,items:['Book','Coin','Globe','Key','Lamp','Mask'],setup:'Place the six objects into a 2×3 grid.',clues:['The Globe is in the upper-middle cell.','The Key is directly below the Globe.','The Book and the Coin are the two objects flanking the Globe.','The Lamp is directly below the Book.','The Mask is directly below the Coin.','The Book is to the left of the Coin.'],question:'Place all six objects in their correct cells.',answer:['Book','Globe','Coin','Lamp','Key','Mask'],key:'Globeを上段中央、Book/Coinが両側。最後のBook left of Coinで鏡像を消し、下段はdirectly below。',first:'flanking だけでは左右が未確定。left of で向きを決めます。',expressions:['upper-middle cell','flanking','to the left of','directly below']}});
P.push({clues:[
Q('d4_01','Grid / Placement','The vase is not in the top row or the rightmost column.','花瓶は上段にも右端列にもない。',['上段か右端列のどちらかにはある。','上段だけ禁止で右端列はよい。','右端列だけ禁止で上段はよい。'],'not A or B','negated-union'),
Q('d4_02','Scheduling','The call occurs at least two days after the briefing.','電話は説明会の少なくとも2日後に行われる。',['電話は説明会のちょうど2日後。','電話は説明会の最大2日後。','電話は説明会より前。'],'at least two days after','minimum-gap'),
Q('d4_03','Conditional','Ava is eligible provided that Ben is selected.','ベンが選ばれていれば、アヴァは資格を得る。Ben→Ava。',['Ava→Benを意味する。','AvaとBenは同値。','Avaが選ばれない限りBenも選べない。'],'provided that','if-direction'),
Q('d4_04','Ordering / Ranking','Cara finishes no more than two places behind Diego.','カーラはディエゴより後ろだが、差は最大2順位。',['カーラは少なくとも2つ後ろ。','カーラはちょうど2つ後ろ。','カーラはディエゴより前。'],'no more than two places behind','bounded-distance'),
Q('d4_05','Grid / Placement','The star is adjacent to the moon along an edge, not diagonally.','星は月と辺を共有する隣接マスにあり、斜め隣ではない。',['星は月の斜め隣。','星は月の周囲8マスならどこでもよい。','星は月と同じ行なら離れていてもよい。'],'along an edge, not diagonally','orthogonal-adjacency'),
Q('d4_06','Assignment / Matching','The person assigned Monday is either Eli or Fiona.','月曜担当者はイーライかフィオナのどちらか。',['イーライとフィオナの両方が月曜担当。','月曜担当は2人以外。','イーライが月曜と確定。'],'either A or B','two-candidate'),
Q('d4_07','Selection / Grouping','No two of Grace, Henry, and Isla may be selected together.','グレース、ヘンリー、アイラから同時に選べるのは最大1人。',['3人からちょうど2人選ぶ。','少なくとも2人選ぶ。','3人全員選べる。'],'no two ... together','at-most-one'),
Q('d4_08','Mixed / Quantifier','Every room except Room 4 is occupied.','4号室以外の全室が使用中で、4号室だけが例外。',['4号室だけが使用中。','4号室を含む全室が使用中。','少なくとも1室空いていれば場所はどこでもよい。'],'every ... except','single-exception'),
Q('d4_09','Grid / Placement','The ring is in the same column as the crown, with exactly one cell between them.','指輪と王冠は同じ列で、間にちょうど1マスある。',['2つは上下に隣接する。','間に2マスある。','同じ行にある。'],'same column + one between','gap-vs-distance'),
Q('d4_10','Truth-teller / Liar','At most one of the three speakers is lying.','3人のうち嘘をついているのは最大1人。全員真実でもよい。',['嘘つきはちょうど1人。','少なくとも1人は嘘つき。','嘘つきは最大2人。'],'at most one lying','at-most')],mini:{id:'daily_m4',category:'Daily / Scheduling',englishDifficulty:3,logicDifficulty:2,setup:'Five events—Audit, Briefing, Call, Demo, and Expo—occur one per day from Monday through Friday.',clues:['The Call occurs on Friday.','The Demo occurs immediately before the Call.','The Audit occurs before the Briefing.','The Expo occurs immediately after the Briefing.'],question:'What occurs on Wednesday?',choices:['Audit','Briefing','Demo','Expo'],answer:'Expo',key:'Call=Fri, Demo=Thu。Audit<Briefing–Expo の連続ペアはMon–Tue–Wedにしか入らず、Expo=Wed。',first:'Friday固定からDemo=Thursdayを先に確定します。',expressions:['immediately before','before','immediately after']}});
P.push({clues:[
Q('d5_01','Grid / Placement','The mask is diagonally opposite the crown in a 2×2 block.','2×2の範囲でマスクと王冠は対角の位置にある。',['2つは辺を共有する。','2つは同じ行。','2つは同じ列。'],'diagonally opposite','diagonal-relation'),
Q('d5_02','Ordering / Ranking','Ben is the third person after Ava.','ベンはアヴァの後に数えて3番目、つまり間に2人いる。',['ベンはアヴァの3つ後で間に3人いる。','ベンはアヴァの直後。','ベンはアヴァの3つ前。'],'third person after','ordinal-vs-gap'),
Q('d5_03','Conditional','Cara cannot attend unless Diego attends.','カーラが参加するにはディエゴの参加が必要。Cara→Diego。',['Diego→Cara。','CaraとDiegoは必ず参加。','CaraとDiegoは同時参加不可。'],'cannot ... unless','unless-necessity'),
Q('d5_04','Selection / Grouping','At least one of Eli and Fiona must be selected.','イーライとフィオナの少なくとも一方を選ぶ。両方でもよい。',['ちょうど一方だけ選ぶ。','両方選ぶ必要がある。','どちらも選ばなくてよい。'],'at least one','inclusive-or'),
Q('d5_05','Grid / Placement','The cup is two cells to the left of the plate in the same row.','カップと皿は同じ行で、カップは皿より位置差2マス左。間には1マスある。',['間に2マスある。','左右隣。','別の行でもよい。'],'two cells to the left in same row','distance-vs-gap'),
Q('d5_06','Scheduling','The tour cannot be scheduled before Wednesday.','見学は水曜以降にしか予定できない。水曜も含む。',['見学は水曜以前。','見学は木曜以降で水曜は不可。','見学は水曜ちょうど。'],'cannot be before','inclusive-lower-bound'),
Q('d5_07','Assignment / Matching','Neither the engineer nor the teacher chose the red card.','技師も教師も赤いカードを選んでいない。',['技師か教師の一方が赤。','2人とも赤。','技師だけ赤ではなく教師は赤でもよい。'],'neither ... nor','neither-nor'),
Q('d5_08','Mixed / Quantifier','Fewer than half of the eight players advance.','8人の半数未満、つまり進出は0〜3人。',['4人以下。','4人以上。','ちょうど3人。'],'fewer than half','strict-bound'),
Q('d5_09','Grid / Placement','The object in the lower-left corner is directly beneath the coin.','左下隅の物はコインの真下1マスにある。',['コインが左下隅にある。','左下隅の物はコインより下なら離れてもよい。','左下隅の物はコインの右隣。'],'referential directly beneath','reference-direction'),
Q('d5_10','Truth-teller / Liar','Alice and Bob are the same type, while Carol is the opposite type.','アリスとボブは同じ真偽タイプで、キャロルはその反対タイプ。',['3人とも同じタイプ。','アリスとボブが反対タイプ。','キャロルはアリスと同じタイプ。'],'same type / opposite type','type-relation')],mini:{id:'daily_m5',category:'Daily / Truth & Lies',englishDifficulty:3,logicDifficulty:2,setup:'Alice, Bob, and Carol are each either a truth-teller or a liar.',clues:['Alice says, “Bob is a liar.”','Bob says, “Carol is a liar.”','Carol says, “Alice and Bob are different types.”'],question:'Who is the truth-teller?',choices:['Alice only','Bob only','Carol only','Alice and Carol'],answer:'Bob only',key:'Aliceが真ならBob偽→Bobの発言は偽なのでCarol真となるがCarol発言と矛盾。よってAlice偽、Bob真、Carol偽。',first:'Alice=true を仮定して短く矛盾を見ると速いです。',expressions:['is a liar','different types','truth-teller']}});
P.push({clues:[
Q('d6_01','Grid / Placement','The candle is in a cell sharing neither a row nor a column with the bell.','ろうそくとベルは同じ行でも同じ列でもない。',['同じ行か列のどちらか。','必ず斜め隣。','同じ列だが行は違う。'],'sharing neither a row nor a column','neither-axis'),
Q('d6_02','Ordering / Ranking','Diego finishes somewhere ahead of Eli, with at least one runner between them.','ディエゴはイーライより前で、間に少なくとも1人いる。',['ディエゴはイーライの直前。','間にはちょうど1人。','ディエゴはイーライより後。'],'ahead with at least one between','direction-plus-gap'),
Q('d6_03','Conditional','If Fiona is selected, then Grace is not selected.','フィオナが選ばれたらグレースは選ばれない。',['グレースが不選択ならフィオナが選ばれる。','フィオナとグレースは両方選ばれる。','フィオナが不選択ならグレースも不選択。'],'if ... not','conditional-negation'),
Q('d6_04','Scheduling','The meeting occurs on either Monday or Wednesday, but not both.','会議日は月曜か水曜のどちらか一方。',['月曜と水曜の両方。','月〜水のどこか。','月曜か水曜の少なくとも一方で両方でもよい。'],'either ... but not both','exclusive-or'),
Q('d6_05','Grid / Placement','The triangle lies somewhere between the square and the circle in the same column.','三角形は四角形と円と同じ列で、上下方向に2つの間にある。隣接とは限らない。',['3つは同じ行。','三角形は2つの両方に必ず隣接。','三角形は2つの外側。'],'somewhere between in same column','between-vs-adjacent'),
Q('d6_06','Assignment / Matching','The person assigned the blue folder arrived earlier than Henry.','青いフォルダ担当者はヘンリーより早く到着した。',['青担当者はヘンリーの直前に限る。','青担当者はヘンリーより遅い。','ヘンリーが青担当。'],'referential earlier than','reference-order'),
Q('d6_07','Selection / Grouping','Exactly two of Isla, Jack, Kevin, and Laura are selected.','4人のうち選ばれるのはちょうど2人。',['少なくとも2人。','最大2人。','2人以外なら何人でもよい。'],'exactly two of four','exact-count'),
Q('d6_08','Mixed / Quantifier','No more than three of the seven switches may be on.','7個のスイッチのうちONは最大3個。0〜3個。',['少なくとも3個ON。','ちょうど3個ON。','最大4個ON。'],'no more than three','at-most'),
Q('d6_09','Grid / Placement','The book is not adjacent to any corner cell.','本は四隅のどのマスとも隣接していない。',['本は隅のどれかにある。','本は少なくとも1つの隅に隣接する。','本は外周にないという意味だけである。'],'not adjacent to any corner','quantified-adjacency'),
Q('d6_10','Truth-teller / Liar','All but one of the four speakers are telling the truth.','4人中3人が真実を言い、1人だけが嘘をついている。',['真実は1人だけ。','少なくとも3人真実なら4人全員でもよい。','2人真実、2人嘘。'],'all but one','all-but-one')],mini:{id:'daily_m6',mode:'grid-placement',category:'Daily / Object Placement',englishDifficulty:4,logicDifficulty:2,rows:2,cols:3,items:['Crown','Gem','Key','Map','Ring','Torch'],setup:'Place the six objects into a 2×3 grid.',clues:['The Map is in the upper-middle cell.','The Key is directly below the Map.','The Crown and the Ring are the two objects adjacent to the Map in its row.','The Gem is directly below the Crown.','The Torch is directly below the Ring.','The Crown is to the right of the Ring.'],question:'Place all six objects in their correct cells.',answer:['Ring','Map','Crown','Torch','Key','Gem'],key:'Map中央。Crown/Ringが左右隣で、Crown right of Ringにより向き確定。下段は縦対応。',first:'adjacent pairだけだと鏡像が残るので、方向clueで向きを決めます。',expressions:['adjacent to','in its row','to the right of','directly below']}});
window.DAILY_START='2026-09-07';window.DAILY_PACKS=P;
})();