(()=>{window.addEventListener('DOMContentLoaded',()=>{
const miniScreen=$('miniScreen'),feedback=$('miniFeedback');
const style=document.createElement('style');style.textContent=`.gridWrap{margin-top:16px}.gridHelp{margin:8px 0 12px}.gridPalette{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 16px}.gridToken{background:#252d4c;color:var(--text);border:1px solid var(--border);border-radius:999px;padding:9px 12px;font-weight:700}.gridToken.selected{outline:2px solid var(--accent);background:#303b65}.gridBoard{display:grid;gap:8px;max-width:620px;margin:0 auto}.gridCell{position:relative;min-height:92px;background:#1d233b;border:2px dashed #3b456e;border-radius:13px;color:var(--text);padding:26px 8px 8px;text-align:center;font-weight:800}.gridCell.filled{border-style:solid;background:#252d4c}.gridCell.cellCorrect{border-color:var(--good);background:rgba(73,209,125,.14)}.gridCell.cellWrong{border-color:var(--bad);background:rgba(255,107,122,.13)}.gridPos{position:absolute;top:6px;left:8px;font-size:10px;color:var(--muted);font-weight:500}.gridStatus{min-height:20px;margin-top:10px}.gridSolution{line-height:1.7}.gridActions{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}@media(max-width:650px){.gridCell{min-height:78px;font-size:14px;padding-top:24px}.gridPos{font-size:9px}}`;document.head.appendChild(style);
const wrap=document.createElement('div');wrap.id='miniGridWrap';wrap.className='gridWrap hidden';wrap.innerHTML=`<div class="small muted gridHelp">アイテムをタップ → マスをタップで配置。配置済みのマスをタップすると持ち上げられます。</div><div id="gridPalette" class="gridPalette"></div><div id="gridBoard" class="gridBoard"></div><div id="gridStatus" class="small muted gridStatus"></div><div class="gridActions"><button id="gridResetBtn" class="secondary">配置をリセット</button><button id="gridCheckBtn" class="primary">配置を判定</button></div>`;feedback.before(wrap);
let gridState=[],selectedItem=null;
const posNames=['upper-left','upper-middle','upper-right','lower-left','lower-middle','lower-right'];
function setCommonMini(){miniLocked=false;if(miniRaf)cancelAnimationFrame(miniRaf);showScreen('miniScreen');feedback.classList.add('hidden');const oldSol=document.getElementById('miniGridSolution');if(oldSol)oldSol.remove();$('miniCategory').textContent=currentMini.category;$('miniDifficulty').textContent=`EN ${stars(currentMini.englishDifficulty)} / Logic ${stars(currentMini.logicDifficulty)}`;$('miniSetup').textContent=currentMini.setup;$('miniClues').innerHTML='';currentMini.clues.forEach(c=>{const li=document.createElement('li');li.textContent=c;$('miniClues').appendChild(li)});$('miniQuestion').textContent=currentMini.question;$('miniSource').innerHTML='';}
function startMiniExtended(){if(!miniDeck.length)refillMiniDeck();currentMini=miniDeck.pop();setCommonMini();if(currentMini.mode==='grid-placement')renderGridPuzzle();else renderChoicePuzzle();miniStartedAt=performance.now();updateMiniTimer()}
function renderChoicePuzzle(){wrap.classList.add('hidden');$('miniOptions').classList.remove('hidden');$('miniOptions').innerHTML='';shuffle(currentMini.choices).forEach(text=>{const b=document.createElement('button');b.className='option';b.textContent=text;b.onclick=()=>answerMini(b,text);$('miniOptions').appendChild(b)})}
function renderGridPuzzle(){$('miniOptions').classList.add('hidden');$('miniOptions').innerHTML='';wrap.classList.remove('hidden');gridState=Array(currentMini.rows*currentMini.cols).fill(null);selectedItem=null;$('gridStatus').textContent='';renderGrid();}
function renderGrid(){const palette=$('gridPalette'),board=$('gridBoard');palette.innerHTML='';board.innerHTML='';board.style.gridTemplateColumns=`repeat(${currentMini.cols},1fr)`;currentMini.items.filter(x=>!gridState.includes(x)).forEach(item=>{const b=document.createElement('button');b.className='gridToken'+(selectedItem===item?' selected':'');b.textContent=item;b.onclick=()=>{if(miniLocked)return;selectedItem=selectedItem===item?null:item;renderGrid()};palette.appendChild(b)});gridState.forEach((item,i)=>{const c=document.createElement('button');c.className='gridCell'+(item?' filled':'');c.innerHTML=`<span class="gridPos">${posNames[i]||`cell ${i+1}`}</span><span>${item?esc(item):'—'}</span>`;c.onclick=()=>{if(miniLocked)return;if(selectedItem){const oldIndex=gridState.indexOf(selectedItem);if(oldIndex>=0)gridState[oldIndex]=null;gridState[i]=selectedItem;selectedItem=null;}else if(gridState[i]){selectedItem=gridState[i];gridState[i]=null;}renderGrid()};board.appendChild(c)});}
function fillFeedback(correct,elapsed){$('miniFeedbackTitle').className='feedbackTitle '+(correct?'ok':'ng');$('miniFeedbackTitle').textContent=correct?'✓ 正解':'✗ 不正解';$('miniTimeResult').textContent=`Time: ${elapsed.toFixed(1)} s`;$('miniKey').textContent=currentMini.key;$('miniFirst').textContent=currentMini.first;$('miniExpressions').innerHTML='';currentMini.expressions.forEach(x=>{const s=document.createElement('span');s.className='chip';s.textContent=x;$('miniExpressions').appendChild(s)});const src=currentMini.source||{label:'Original'};$('miniSource').innerHTML=src.url?`<a class="sourceLink" href="${esc(src.url)}" target="_blank" rel="noopener">${esc(src.label)}</a>${src.note?`<div class="small muted">${esc(src.note)}</div>`:''}`:esc(src.label||'Original');let sol=document.getElementById('miniGridSolution');if(!sol){sol=document.createElement('div');sol.id='miniGridSolution';sol.className='feedbackRow';$('miniSource').parentElement.after(sol)}sol.innerHTML=`<strong>正解配置</strong><div class="gridSolution">Top: ${currentMini.answer.slice(0,currentMini.cols).map(esc).join(' ｜ ')}<br>Bottom: ${currentMini.answer.slice(currentMini.cols).map(esc).join(' ｜ ')}</div>`;feedback.classList.remove('hidden');feedback.scrollIntoView({behavior:'smooth',block:'nearest'});}
function checkGrid(){if(miniLocked)return;if(gridState.some(x=>!x)){$('gridStatus').textContent='まだ空いているマスがあります。6個すべて配置してから判定。';return;}miniLocked=true;const elapsed=(performance.now()-miniStartedAt)/1000;cancelAnimationFrame(miniRaf);miniRaf=null;const correct=gridState.every((x,i)=>x===currentMini.answer[i]);[...$('gridBoard').children].forEach((c,i)=>c.classList.add(gridState[i]===currentMini.answer[i]?'cellCorrect':'cellWrong'));$('gridStatus').textContent=correct?'配置はすべて正しいです。':'赤いマスが不一致。下の正解配置と比較してください。';fillFeedback(correct,elapsed)}
$('gridResetBtn').onclick=()=>{if(miniLocked)return;gridState=Array(currentMini.rows*currentMini.cols).fill(null);selectedItem=null;$('gridStatus').textContent='';renderGrid()};$('gridCheckBtn').onclick=checkGrid;
$('startMiniBtn').onclick=startMiniExtended;$('nextMiniBtn').onclick=startMiniExtended;const f=document.querySelector('footer');if(f)f.textContent=`English Clue Sprint v1.7 — ${BANK.length} clues + ${MINI_PUZZLES.length} Mini Puzzles`;
});})();