-- English Clue Sprint: Daily leaderboard backend
-- Frontend uses Supabase anonymous auth. Users still see only a display-name prompt.

create table if not exists public.daily_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  display_name text not null check (char_length(display_name) between 1 and 24),
  daily_date date not null,
  clue_score smallint not null check (clue_score between 0 and 10),
  mini_correct boolean not null,
  score smallint not null check (score between 0 and 11),
  reading_time_ms integer not null check (reading_time_ms >= 0),
  answer_time_ms integer not null check (answer_time_ms >= 0),
  mini_time_ms integer not null check (mini_time_ms >= 0),
  total_time_ms integer not null check (total_time_ms >= 0),
  completed_at timestamptz not null default now(),
  unique (user_id, daily_date)
);

alter table public.daily_results enable row level security;

create policy "daily results readable by players"
on public.daily_results for select
to authenticated
using (true);

create policy "players insert their own daily result"
on public.daily_results for insert
to authenticated
with check (auth.uid() = user_id);

create index if not exists daily_results_rank_idx
on public.daily_results (daily_date, score desc, total_time_ms asc);

-- Also enable Anonymous Sign-Ins in Supabase Auth settings.
